name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build & Test
    uses: ./.github/workflows/_build-test.yml
    with:
      test-filter: 'TestCategory!=Live'
